name: Create Tag on package.json update

on:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
        fetch-depth: 0
    - uses: butlerlogic/action-autotag@1.1.4
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        tag_prefix: "v"
