name: github-publish

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  github-publish:
    name: github-publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        registry-url: "https://npm.pkg.github.com"
        scope: "@oolio-group"
    - name: Install Node Dependencies
      run: npm install
    - name: Download & Build Icons
      run: npm ci --progress=false && npm run generate
    - name: Publish package
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}